import type { Metadata } from "next";
import {NextIntlClientProvider} from 'next-intl';
import {getLocale, getMessages} from 'next-intl/server';
import localFont from "next/font/local";
import "./globals.css";
import SideMenu from "@/components/SideMenu";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = Readonly<{
	children: React.ReactNode
}>

export default async function RootLayout(props: RootLayoutProps) {
	const { children } = props

	const locale = await getLocale();

	// Providing all messages to the client
	// side is the easiest way to get started
	const messages = await getMessages();
	return (
		<html lang={locale}>
		<body
			className={`${geistSans.variable} ${geistMono.variable} antialiased flex min-h-screen`}
		>
		<NextIntlClientProvider messages={messages}>
			<SideMenu/>
			<main className="flex-1 px-10 py-6">
				{children}
			</main>
		</NextIntlClientProvider>
		</body>
		</html>
	);
}
