name: Deploy Next.js to Docker Registry

on:
  push:
    tags:
      - 'v*.*.*'  # Déclenché lors d'un push de tag versionné (ex: v1.2.3)

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: 🔽 Checkout du code
        uses: actions/checkout@v3

      - name: 🐳 Se connecter à Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: 🏷️ Extraire la version depuis le tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: 🔨 Build de l’image Docker avec tags versionnés
        run: |
          docker build -f production.Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/stock-buster-front:${{ env.VERSION }} .
          docker build -f production.Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/stock-buster-front:latest .

      - name: 📤 Push des images Docker
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/stock-buster-front:${{ env.VERSION }}
          docker push ${{ secrets.DOCKER_USERNAME }}/stock-buster-front:latest

      - name: 🔄 Déclencher le redeploiement sur Coolify
        run: |
          curl -X POST "https://coolify.timothee-picard.dev/api/v1/deploy?uuid=ekso88soo40k8kkc4g8o4ks4&force=false" \
          -H "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}"
